Repository skyra-project/teryl, pull requests merged in 2024-04, with the labels that each got.

#224 fix(reddit): handle shortlinks
  package.json
  src/commands/reddit.ts
  yarn.lock
Labels: priority:high

#228 refactor(reddit): improve errors and handling
  src/commands/reddit.ts
  src/lib/i18n/LanguageKeys/Commands/Reddit.ts
  src/locales/en-US/commands/reddit.json
Labels: priority:high, regression

#231 feat(reminders): add option to send silent messages
  prisma/migrations/20240421171101_04_add_silent_reminders/migration.sql
  prisma/schema.prisma
  src/commands/reminders.ts
  src/lib/common/constants.ts
  src/lib/i18n/LanguageKeys/Commands/Reminders.ts
  src/locales/en-US/commands/reminders.json
  src/schedule-handlers/reminders.ts
Labels: feature
